FightCorona/urls.py
# from django.contrib import admin
from django.contrib import admin
from django.urls import path
from FightCorona import views
from django.urls import include, path
from francis import views as francis_views
from .settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from errorhandling import views as views1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page),
    path('forum', francis_views.index, name='francis'),
    path('forum/new_post', francis_views.upload),
    path('tentang', views.about),
    path('edukasi/', include('farah.urls'), name="farah"),
    path('maskermu/', include('jati.urls'), name="jati"),
    path('olahraga/', include('alfath.urls'), name="alfath"),
    path('rehat/', include('tijani.urls'), name="tijani"),

]

urlpatterns += static(STATIC_URL, document_root = STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

handler404 = views1.notFound

jati/urls.py
from django.urls import path

from . import views

app_name = 'jati'

urlpatterns = [
    path('', views.maskermu, name='maskermu'),
    path('listpengalaman/', views.listpengalaman, name='listpengalaman'),
]

tijani/urls.py
from django.urls import path
from . import views

app_name = 'tijani'

urlpatterns = [
    path('', views.rehat, name='rehat'),
    path('listTanggapan/', views.listTanggapan, name='listTanggapan'),
    path('menuPagi/', views.menuPagi, name='menuPagi'),
    path('menuSiang/', views.menuSiang, name='menuSiang'),
    path('menuMalam/', views.menuMalam, name='menuMalam'),
    path('makananRingan/', views.makananRingan, name='makananRingan'),
    path('minuman/', views.minuman, name='minuman'),
]

tijani/models.py
from django.db import models

# Create your models here.
class Tanggapan(models.Model):
    list_tanggapan = models.CharField(max_length=100)

    def __str__(self):
        return self.list_tanggapan

tijani/forms.py
from django import forms


class FormTanggapan(forms.Form):
    list_tanggapan = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Tulis tanggapanmu disini...',
                'type': 'text',
                'required': True
            }))

tijani/views.py
from django.shortcuts import redirect, render
from .forms import FormTanggapan
from .models import Tanggapan

# Create your views here.
def rehat(request):
    form_tanggapan = FormTanggapan()
    if request.method == 'POST':
        form_fix = FormTanggapan(request.POST)
        if (form_fix.is_valid()):
            tanggapan = Tanggapan()
            tanggapan.list_tanggapan = form_fix.cleaned_data['list_tanggapan']
            tanggapan.save()
        return redirect('/rehat/listTanggapan')
    else:
        form = FormTanggapan()
        tanggapan = Tanggapan.objects.all()
        context = {
            'Form': form,
            'Tanggapan': tanggapan
        }
    return render(request, 'home.html', context)

def listTanggapan(request):
    tanggapan = Tanggapan.objects.all()
    return render(request, 'feedback.html', {'listTanggapan': tanggapan})

def menuPagi(request):
    return render(request, 'breakfast.html')

def menuSiang(request):
    return render(request, 'lunch.html')

def menuMalam(request):
    return render(request, 'dinner.html')

def makananRingan(request):
    return render(request, 'snacks.html')

def minuman(request):
    return render(request, 'beverages.html')

tijani/templates/beverages.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}
<html lang="en">
<title> Rehat Beverages</title>

{% block meta %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}
<body>
    <section class="beverages">
        <div>
            <img class = "bev-rec1" src="{% static 'pics/rec1bev.png' %}">
            <img class = "bev1" src="{% static 'pics/1bev.png' %}">
            <img class = "bev-footer" src="{% static 'pics/footerbev.png' %}">
        </div>
    </section>

</body>
{% endblock content %}

tijani/templates/breakfast.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}
<html lang="en">
<title> Rehat Breakfast </title>
{% block meta %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

    <style>
        body{
            background-color: white;
        }
    </style>
{% endblock meta %}

{% block content %}
<body>
    <section class="breakfast">

        <div>
            <img class = "br-rec1" src="{% static 'pics/rec1br.png' %}">
            <img class = "br1" src="{% static 'pics/1br.png' %}">
            <img class = "br2" src="{% static 'pics/2br.png' %}">
            <img class = "br3" src="{% static 'pics/3br.png' %}">
            <img class = "br-footer" src="{% static 'pics/footerbr.png' %}">
        </div>
    </section>

</body>
{% endblock content %}

tijani/templates/dinner.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}
<html lang="en">
<title> Rehat Dinner</title>

{% block meta %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}

<body>
    <section class="dinner">
        <div>
            <img class = "dn-rec1" src="{% static 'pics/rec1dinner.png' %}">
            <img class = "dn1" src="{% static 'pics/1dinner.png' %}">
            <img class = "dn2" src="{% static 'pics/2dinner.png' %}">
            <img class = "dn-footer" src="{% static 'pics/footerdinner.png' %}">
        </div>
    </section>

</body>
{% endblock content %}

tijani/templates/feedback.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<style>
    body{
        background-color: #374785 ;
    }
    .button {
        background-color: #A8D0E6;;
        border-radius: 15px;
        padding: 10px 24px;
        text-align: center;
        color: #F76C6C;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        font-family: "Poppins";
        font-weight: bold;
    }

    .button:hover {
        background-color: white;
        color: #374785;
    }

    .font1 {
        font-family: Poppins;
        font-style: normal;
        font-weight: bold;
        font-size: 24px;
        line-height: 36px;
        display: flex;
        color: #A8D0E6;
    }

    .font2 {
        font-family: Poppins;
        font-style: normal;
        font-weight: 600;
        font-size: 24px;
        line-height: 36px;
        display: flex;
        color: #F76C6C;
    }
    
</style>
{% endblock meta %}

{% block content %}

<br>
<br>
<br>

<h1 align="center" class="font1"> Tanggapan Resep Rehat: </h1>
<br><br>


{% for x in listTanggapan %}
   <p align = "center" class = "font2"> {{x.list_tanggapan}} </p>
{% endfor %}



<br>
<div align = "center">
<a href="{% url 'tijani:rehat' %}"><button align="center" class="button">Kembali</button> </a>
</div>
{% endblock content %}

tijani/templates/home.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
<html lang="en">
<title> Rehat Home </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

    <style>
        body{
        background-color: #374785 ;
        }
        
        .button {
            background-color: #A8D0E6;;
            border-radius: 15px;
            padding: 10px 24px;
            text-align: center;
            color: #F76C6C;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            font-family: "Poppins";
            font-weight: bold;
        }
    
        .button:hover {
            background-color: white;
            color: #374785;
        }
    
        .font1 {
            position: absolute;
            width: 246px;
            height: 58px;
            left: 517px;
            top: 1396px;
    
            font-family: Poppins;
            font-style: normal;
            font-weight: bold;
            font-size: 24px;
            line-height: 36px;
            display: flex;
            align-items: center;
            text-align: center;
    
            color: #A8D0E6;
        }
    
        .font2 {
            font-family: Poppins;
            font-style: normal;
            font-weight: 600;
            font-size: 24px;
            line-height: 36px;
            display: flex;
            align-items: center;
            text-align: center;
    
            color: #F76C6C;
        }

    </style>
{% endblock meta %}

{% block content %}

<body>
    <section class="home">
        <div>
            <img class = "home-title" src="{% static 'pics/Titlerec.png' %}">
            <img class = "home-rec1" src="{% static 'pics/Recpink.png' %}">
        </div>
        <div> 
            <a class = "home-br" href="{% url 'tijani:menuPagi' %}">
                <img src="{% static 'pics/Breakfastcir1.png' %}" style="position: absolute;
                width: 200px;
                height: 200px;
                left: 231px;
                top: 600px;">
                </a>
            <a class = "home-lch" href="{% url 'tijani:menuSiang' %}">
                <img src="{% static 'pics/Lunchcir2.png' %}" style="position: absolute;
                width: 200px;
                height: 200px;
                left: 543px;
                top: 600px;">
                </a>
            <a class = "home-dnr" href="{% url 'tijani:menuMalam' %}">
                <img src="{% static 'pics/Dinnercir3.png' %}" style="position: absolute;
                width: 200px;
                height: 200px;
                left: 855px;
                top: 600px;">
                </a>
            <a class = "home-sn" href="{% url 'tijani:makananRingan' %}">
                <img src="{% static 'pics/Snackscir4.png' %}" style="position: absolute;
                width: 200px;
                height: 200px;
                left: 368px;
                top: 833px;">
                </a>
            <a class = "home-bev" href="{% url 'tijani:minuman' %}">
                <img src="{% static 'pics/Beveragescir5.png' %}" style="position: absolute;
                width: 200px;
                height: 200px;
                left: 708px;
                top: 833px;">
                </a>
        </div>
        <p1>Disaat masa pandemi sekarang, penting sekali
             untuk tetap menjaga pola makan dengan baik. 
             Tentunya pola makan tersebut didukung dengan 
             makanan yang bergizi dan sehat. </p1>
        <p2>Yuk Ikutin Resepnya!</p2>
        <p3>BAGAIMANA RESEPNYA?</p3>
    </section>

    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>
    <br><br><br><br><br><br><br><br><br><br>
    <br><br>


    <form class=formpost action='' method="POST" margin="20px">
        {% csrf_token %}
        {{ Form }}
        <br>
        <div align="center" >
            <input type="submit" class="button" value="Submit">
        </div>
    </form>

    <br>
    <br>

    <div align="center">
    <a href="{% url 'tijani:listTanggapan' %}"><button class="button">Cek Tanggapan</button> </a>
        </div>
</body>
{% endblock content %}

tijani/templates/lunch.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}
<html lang="en">
<title> Rehat Lunch</title>

{% block meta %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}

<body>
    <section class="lunch">
        <div>
            <img class = "lch-rec1" src="{% static 'pics/rec1lunch.png' %}">
            <img class = "lch1" src="{% static 'pics/1lunch.png' %}">
            <img class = "lch2" src="{% static 'pics/2lunch.png' %}">
            <img class = "lch-footer" src="{% static 'pics/footerlunch.png' %}">
        </div>
    </section>

</body>
{% endblock content %}

tijani/templates/snacks.html
<!DOCTYPE html>

{% extends 'global/base.html' %}
{% load static %}
<html lang="en">
<title> Rehat Snacks</title>

{% block meta %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'rehat.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
{% endblock meta %}

{% block content %}

<body>
    <section class="snacks">
        <div>
            <img class = "sn-rec1" src="{% static 'pics/rec1snacks.png' %}">
            <img class = "sn1" src="{% static 'pics/1snacks.png' %}">
            <img class = "sn2" src="{% static 'pics/2snacks.png' %}">
            <img class = "sn-footer" src="{% static 'pics/footersnacks.png' %}">
        </div>
    </section>

</body>
{% endblock content %}