FightCorona/urls.py
# from django.contrib import admin
from django.contrib import admin
from django.urls import path
from FightCorona import views
from django.urls import include, path
from francis import views as francis_views
from .settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from errorhandling import views as views1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page),
    path('forum', francis_views.index, name='francis'),
    path('forum/new_post', francis_views.upload),
    path('tentang', views.about),
    path('edukasi/', include('farah.urls'), name="farah"),
    path('maskermu/', include('jati.urls'), name="jati"),
    path('olahraga/', include('alfath.urls'), name="alfath"),
    path('rehat/', include('tijani.urls'), name="tijani"),

]

urlpatterns += static(STATIC_URL, document_root = STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

handler404 = views1.notFound

jati/urls.py
from django.urls import path

from . import views

app_name = 'jati'

urlpatterns = [
    path('', views.maskermu, name='maskermu'),
    path('listpengalaman/', views.listpengalaman, name='listpengalaman'),
]

jati/models.py
from django.db import models

# Create your models here.


class Pengalaman(models.Model):
    cerita_pengalaman = models.CharField(max_length=1000)

    def __str__(self):
        return self.cerita_pengalaman

jati/forms.py
from django import forms


class FormPengalaman(forms.Form):
    cerita_pengalaman = forms.CharField(
        max_length=1000,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'tulis disini',
                'type': 'text',
                'required': True
            }))

jati/views.py
from django.shortcuts import render, redirect
from .forms import FormPengalaman
from .models import Pengalaman
# Create your views here.


def maskermu(request):
    form_pengalaman = FormPengalaman()
    if request.method == 'POST':
        form_fix = FormPengalaman(request.POST)
        if (form_fix.is_valid()):
            pengalaman = Pengalaman()
            pengalaman.cerita_pengalaman = form_fix.cleaned_data['cerita_pengalaman']
            pengalaman.save()
        return redirect('/maskermu/listpengalaman')
    else:
        form = FormPengalaman()
        pengalaman = Pengalaman.objects.all()
        context = {
            'Form': form,
            'pengalaman': pengalaman
        }
        return render(request, 'jati/maskermu.html', context)

def listpengalaman(request) :
    pengalaman = Pengalaman.objects.all()
    return render(request, 'jati/listpengalaman.html', {'listpengalaman': pengalaman})

jati/templates/jati/listpengalaman.html
{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" type="text/css" href="../../static/jati/css/style.css">
    <meta charset="utf-8">
    <title>Pengalamanmu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <style type="text/css">
    	body {
	    	background-color: #A8D0E6;
	    	font-family: Poppins;
	    	width: 80%;
			margin-left: auto;
		    margin-right: auto;
	    }

	    #btn-kembali {
	    	background: #F76C6C;
	    	color: white;
	    	font-family: Roboto;
	    	text-decoration: none;
	    	border-radius: 20px;
	    	padding: 0.8vw;
	    }

    </style>
{% endblock meta %}

{% block content %}

<br>
<br>
<br>
<p style="font-size: 24px;">Pengalamanmu menggunakan masker:</p>
{% for x in listpengalaman %}
<p style="
	border: solid 2px #F76C6C; 
	padding: 1vw;
	border-radius: 25px;
	font-style: italic;
	background: white;
	color: rgb(0,0,0,0.8)">"{{x.cerita_pengalaman}}"</p>
{% endfor %}

<div align="center" >
    <a href="{% url 'jati:maskermu' %}" ><button align="center" class="button" id="btn-kembali">Kembali</button> </a>
</div>

{% endblock content %}

jati/templates/jati/maskermu.html
{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
    <title>Maskermu</title>
<style>
    body {
    	background-color: #A8D0E6;
    	
    }

    @media screen and (min-width: 601px) {
		img.gbr-masker {
			display: block;
		    margin-left: auto;
		    margin-right: auto;
		    width: 25%;
		    overflow: hidden;
		}

		.container {
			width: 80%;
			margin-left: auto;
		    margin-right: auto;
		    font-family: Poppins;
		}

		.smaller-container {
			width: 50%;
			align-items: center;
			margin-left: auto;
		    margin-right: auto;
		    font-family: Poppins;
		}

		.box-masker {
			background: white;
			display: grid;
		    grid-row-gap: 0px;
		    margin: 10px;
		    margin-left: auto;
		    margin-right: auto;
		    align-items: center;
		    border: 0.5vw solid #374785; 
		    width: 50%;
		    border-radius: 30px;
		    font-family: Poppins;
		}

		.judul-desc {
			background: #F76C6C;
			color: white;
			display: grid;
			font-size: 2.1vw;
			width: auto;
			padding: 1.3vw;
			border-radius: 30px;
			font-family: Poppins;

		}

		.border-desc {
			display: flex; 
			justify-content: space-around;
		}

		.deskripsi-masker {
			background: #F76C6C;
			color: white;
			text-align: center;
			border-top: none;
			font-size: 24px;
			border-bottom-left-radius: 30px;
			border-bottom-right-radius: 30px;
			margin: 2%;
			margin-top: none;
			padding: 5vw;
			font-family: Poppins;
		}
	    
	    #main-artikel {
	    	font-size: 25px;
	    	font-family: Poppins;

	    }

	    #submit-btn {
	    	background: #F76C6C;
	    	color: white;
	    	font-family: Roboto;
	    	text-decoration: none;
	    	border-radius: 20px;
	    	padding: 0.6vw;
	    	font-family: Poppins;
	    }
	}

	@media screen and (max-width: 600px) {
		img.gbr-masker {
			display: block;
		    margin-left: auto;
		    margin-right: auto;
		    width: 25%;
		    overflow: hidden;
		    font-family: Poppins;
		}

		.container {
			width: 80%;
			margin-left: auto;
		    margin-right: auto;
		    font-family: Poppins;
		}

		.smaller-container {
			width: 50%;
			align-items: center;
			margin-left: auto;
		    margin-right: auto;
		    font-family: Poppins;
		}

		.box-masker {
			background: white;
			display: grid;
		    grid-row-gap: 0px;
		    margin: 10px;
		    margin-left: auto;
		    margin-right: auto;
		    align-items: center;
		    border: 0.5vw solid #374785; 
		    width: 50%;
		    border-radius: 30px;
		    font-family: Poppins;
		}

		.judul-desc {
			background: #F76C6C;
			color: white;
			display: grid;
			font-size: 30px;
			width: auto;
			padding: 1.3vw;
			border-radius: 30px;
			font-family: Poppins;
		}

		.border-desc {
			display: flex; 
			justify-content: space-around;
			font-family: Poppins;
		}

		.deskripsi-masker {
			background: #F76C6C;
			color: white;
			text-align: center;
			border-top: none;
			font-size: 1.7vw;
			border-bottom-left-radius: 30px;
			border-bottom-right-radius: 30px;
			margin: 2%;
			margin-top: none;
			padding: 5vw;
			font-family: Poppins;
		}
	    
	    #main-artikel {
	    	font-size: 1.7vw;
	    	font-family: Poppins;
	    }

	    #submit-btn {
	    	background: #F76C6C;
	    	color: white;
	    	font-family: Roboto;
	    	text-decoration: none;
	    	border-radius: 20px;
	    	padding: 0.8vw;
	    	font-family: Poppins;
	    }
	}
</style>    
{% endblock meta %}

{% block content %}
	<main>
		
            <br>
            <br>
            <br>
		<div >
			<!-- section Judul -->
			<div class="container">
				<div>
					<h2 style="text-transform: uppercase; font-size: 36px; text-align: justify;">
						Yuk, Kenali masker yang sebaiknya kita gunakan, rekomendasi dari WHO lho!
					</h2>
					<hr>
				</div>
				<!-- endsection Judul -->

				<!-- section main_Artikel -->
				<div>
					<article id="main-artikel" style="text-align: justify;">
						Nah, di sini, kita mau ngomongin tentang masker nih, yang di Indonesia, 
						wajib dipakai biar ga ketularan. Tapi kalian tau ga, kalau masker itu banyak jenisnya,
						dan penggunaannya pun berbeda tiap jenisnya. 
						<br>
						<br>
						Buat kalian yang belum atau kurang paham sama jenis-jenis masker, yuk cek di bawah ini.
					</article>
				</div>
			</div>
			<!-- endsection main_Artikel -->

			<!-- section Masker_Kain -->
			<div class="box-masker">
				<div>
					<img src="../../static/jati/img/mKain.png" class="gbr-masker" id="mKain">
				</div>
				<div>
					<div class="border-desc">
						<h4 class="judul-desc">
							Masker Kain
						</h4>
					</div>
				</div>
				<div>
					<article class="deskripsi-masker">
						Masker kain yang dibuat perlu memiliki 3 (tiga) lapisan yaitu lapisan 
						non-anyaman tahan air (depan), microfibre melt-blown kain non-anyaman (tengah), 
						dan kain biasa non-tenunan (belakang). 
						<br>
						<br>
						Masker kain perlu dicuci dan dapat dipakai berkali-kali. 
						Bahan yang digunakan untuk masker kain berupa bahan kain katun, 
						scarf, dan sebagainya.
						<br>
						<br>
						Masker jenis ini bisa digunakan ketika berada di tempat umum 
						dan fasilitas lainnya dengan tetap menjaga jarak aman yakni 1-2 meter.
					</article>
				</div>
			</div>
			<!-- endsection Masker_Kain -->

			<!-- section Masker_2PLY -->
			<div class="box-masker">
				<div>
					<img src="../../static/jati/img/m2PLY.png" class="gbr-masker" id="m2PLY">
				</div>
				<div>
					<div style="display: flex; justify-content: space-around;">
						<h4 class="judul-desc">
							Masker Bedah 2 Ply
						</h4>
					</div>
				</div>
				<div>
					<article class="deskripsi-masker">
						Masker bedah 2 Ply alias urgical Mask 2 Ply ini, 
						hanya terdiri dari 2 lapisan (layers) yaitu lapisan luar 
						dan lapisan dalam tanpa lapisan tengah yang berfungsi sebagai filter.
						<br>
						<br>
						Karena tidak memiliki lapisan filter pada bagian tengah 
						diantara lapisan luar kedap air dan dalam yang langsung kontak dengan kulit, 
						maka tipe masker ini kurang efektif untuk menyaring droplet atau percikan 
						yang keluar dari mulut dan hidug pemakai ketika batuk atau bersin. 
						<br>
						<br>
						Dengan begitu, masker jenis ini hanya direkomendasikan 
						untuk pemakaian masyarakat sehari-hari yang tidak menunjukan 
						gejala-gejala flu atau influenza yang disertai dengan batuk, 
						bersin-bersin, hidung berair, demam, nyeri tenggorokan.
					</article>
				</div>
			</div>
			<!-- endsection Masker_2PLY -->

			<!-- section Masker_3PLY -->
			<div class="box-masker">
				<div>
					<img src="../../static/jati/img/m3PLY.png" class="gbr-masker" id="m3PLY">
				</div>
				<div>
					<div style="display: flex; justify-content: space-around;">
						<h4 class="judul-desc">
							Masker Bedah 3 Ply
						</h4>
					</div>
				</div>
				<div>
					<article class="deskripsi-masker">
						Masker Bedah memiliki tiga lapisan (layers) yaitu lapisan luar 
						kain tanpa anyaman kedap air, lapisan dalam yang merupakan lapisan 
						filter densitas tinggi dan lapisan dalam yang menempel langsung dengan 
						kulit yang berfungsi sebagai penyerap cairan berukuran besar yang keluar 
						dari pemakai ketika batuk maupun bersin.
						<br>
						<br>
						Karena memiliki lapisan filter ini, masker bedah efektif untuk menyaring 
						droplet yang keluar dari pemakai ketika batuk atau bersin. 
						Namun lapisan ini bukan merupakan barier proteksi pernapasan karena 
						tidak bisa melindungi pemakai dari terhirupnya partikel airborne yang lebih kecil. 
						<br>
						<br>
						Dengan begitu, masker ini direkomendasikan untuk masyarakat yang 
						menunjukan gejala-gejala flu atau influenza yakni batuk, bersin- bersin, 
						hidung berair, demam, nyeri tenggorokan. Masker ini juga bisa digunakann 
						oleh tenaga medis di fasilitas layanan kesehatan.
						<br>
						<br>
						Berdasarkan rekomendasi WHO, masker seperti ini agar dipergunakan 
						oleh orang yang berusia 60 tahun ke atas atau mereka yang memiliki kondisi 
						penyakit mendasar, harus mengenakan masker medis dalam situasi di mana 
						jarak fisik tidak memungkinkan.
					</article>
				</div>
			</div>
			<!-- endsection Masker_3PLY -->

			<!-- section Masker_N95 -->
			<div class="box-masker">
				<div>
					<img src="../../static/jati/img/mN95.jpg" class="gbr-masker" id="mN95">
				</div>
				<div>
					<div style="display: flex; justify-content: space-around;">
						<h4 class="judul-desc">
							Masker N95
						</h4>
					</div>
				</div>
				<div>
					<article class="deskripsi-masker">
						Masker N95 adalah masker yang lazim dibicarakan dan merupakan 
						kelompok masker Filtering Facepiece Respirator (FFR) sekali pakai 
						(disposable). Kelompok jenis masker ini memiliki kelebihan tidak hanya 
						melindungi pemakai dari paparan cairan dengan ukuran droplet, tapi 
						juga cairan hingga berukuran aerosol. 
						<br>
						<br>
						Masker jenis ini pun memiliki face seal fit yang ketat sehingga 
						mendukung pemakai terhindar dari paparan aerosol asalkan seal fit 
						dipastikan terpasang dengan benar. 
						<br>
						<br>
						Kelompok masker ini direkomendasikan terutama untuk tenaga kesehatan 
						yang harus kontak erat secara langsung menangani kasus dengan tingkat 
						infeksius yang tinggi seperti pasien positif terinfeksi virus corona Covid-19.
					</article>
				</div>
			</div>
			<!-- endsection Masker_N95 -->

			<!-- section Form -->
			<div align="center" class="smaller-container" style="font-size:1.8vw;">
				<div>
					<p style=" font-size-adjust: auto; ">
						Menurut kamu, mana masker yang paling nyaman?
					</p>
				</div>
				<div>
					<p style="">
						Ceritakan Pengalamanmu!
					</p>
				</div>
			</div>
			<div class="smaller-container" style="font-size: 1.2vw;">
				<form action='' method="POST" margin="20px" >
					{% csrf_token %}
					{{ Form }}
					<div align="center" >
						<input type="submit" class="button" value="Upload Ceritamu!" id="submit-btn">
					</div>
				</form>
			</div>
			<!-- endsection Form -->
		</div>
		
	</main>
	<footer>
		<!-- no entry -->
	</footer>
{% endblock content %}