FightCorona/urls.py
# from django.contrib import admin
from django.contrib import admin
from django.urls import path
from FightCorona import views
from django.urls import include, path
from francis import views as francis_views
from .settings import DEBUG, STATIC_URL, STATIC_ROOT, MEDIA_URL, MEDIA_ROOT
from django.conf.urls.static import static
from errorhandling import views as views1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing_page),
    path('forum', francis_views.index, name='francis'),
    path('forum/new_post', francis_views.upload),
    path('tentang', views.about),
    path('edukasi/', include('farah.urls'), name="farah"),
    path('maskermu/', include('jati.urls'), name="jati"),
    path('olahraga/', include('alfath.urls'), name="alfath"),
    path('rehat/', include('tijani.urls'), name="tijani"),

]

urlpatterns += static(STATIC_URL, document_root = STATIC_ROOT)
urlpatterns += static(MEDIA_URL, document_root = MEDIA_ROOT)

handler404 = views1.notFound

farah/urls.py
from django.urls import path

from . import views

app_name = 'farah'

urlpatterns = [
    path('', views.edukasi, name='edukasi'),
    path('listkegiatan/', views.listkegiatan, name='listkegiatan'),
]

jati/urls.py
from django.urls import path

from . import views

app_name = 'jati'

urlpatterns = [
    path('', views.maskermu, name='maskermu'),
    path('listpengalaman/', views.listpengalaman, name='listpengalaman'),
]

farah/models.py
from django.db import models

# Create your models here.

class Kegiatan(models.Model):
    nama_kegiatan = models.CharField(max_length=100)

    def __str__(self):
        return self.nama_kegiatan

farah/forms.py
from django import forms


class FormKegiatan(forms.Form):
    nama_kegiatan = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'tulis disini',
                'type': 'text',
                'required': True
            }))

farah/views.py
from django.shortcuts import render, redirect
from .forms import FormKegiatan
from .models import Kegiatan
# Create your views here.


def edukasi(request):
    form_kegiatan = FormKegiatan()
    if request.method == 'POST':
        form_fix = FormKegiatan(request.POST)
        if (form_fix.is_valid()):
            kegiatan = Kegiatan()
            kegiatan.nama_kegiatan = form_fix.cleaned_data['nama_kegiatan']
            kegiatan.save()
        return redirect('/edukasi/listkegiatan')
    else:
        form = FormKegiatan()
        kegiatan = Kegiatan.objects.all()
        context = {
            'Form': form,
            'kegiatan': kegiatan
        }
        return render(request, 'farah/edukasi.html', context)

def listkegiatan(request) :
    kegiatan = Kegiatan.objects.all()
    return render(request, 'farah/listkegiatan.html', {'listkegiatan': kegiatan})

farah/templates/farah/edukasi.html
{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
<title>Edukasi</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<style>
    body{
        background-color: #A8D0E6 ;
    }
    .button{
        background-color:#374785;
        border-radius: 15px;
        padding:10px 24px;
        text-align: center;
        color: white;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        font-family: "Poppins";
         font-weight: bold;
    }
    .button:hover {
    background-color: white;
    color: #374785;
    }

      .anotherborder{
    border: solid;
    width: 50%;
    height: 50%;
    background:#374785 ;
    border-radius: 50px;
  }
  .border{
    display: grid;
     background:#374785 ;
     border-radius: 50px;
    grid-row-gap: 2px;
    grid-column-gap: 5px;
    margin: 10px;
    align-items: center;
    grid-template-columns: repeat(auto-fit, minmax(50px, 1fr));
}
  .font1{
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-size: 25px;
    font-weight: bold;
    color: white;
  }
  .font2{
       font-family: 'Poppins';
       font-size: 22px;
    color: #374785;
     font-weight: 900;
  }
  .font3{
    font-family: Georgia, 'Times New Roman', Times, serif;
    font-size: 30px;
    font-weight: bold;
    color: #374785;
  }
</style>    
{% endblock meta %}

{% block content %}
    <br>
    <br>
    <br>
        <div>
           <div align = "center"> 
               <h2 align="center" class="border font1">Langkah Pencegahan</h2>
            </div>
            <br>
            <br>
            <br>
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <p align="center" > <img src="{% static 'farah/img/jaga jarak.jpg' %}" width ="224" height = "200"  class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center" class="font2">Jaga Jarak
                            <br> dengan Orang Lain
                        </p>
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    <p align="center"><img src="{% static 'farah/img/masker.jpg' %}"  width ="200" height = "200"  class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center"  class="font2">Pakai Masker
                            <br>Ketika Keluar</p>
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    <p align="center"><img src="{% static 'farah/img/cuci tangan.jpeg' %}"   width ="224" height = "200" class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center"  class="font2">Rajin Mencuci
                            <br>Tangan dengan Sabun</p>
                    </div>
                </div>
            </div>
        </div>

<br>
        <br>
        <br>
        <br>
        <div>
            <div align="center">
                <h2 align="center" class="border font1">Kenali Gejala Covid!</h2>
            </div>
            <br>
            <br>
            <br>
            <div class="row">
                <div class="col-lg-4 mx-auto">
                    <p align="center"> <img src="{% static 'farah/img/demam.jpg' %}"  width ="290" height = "200"  class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center"  class="font2">Demam, Letih,
                            <br>dan Lesu</p>
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    <p align="center"><img src="{% static 'farah/img/batuk.jpg' %}"  width ="290" height = "200"  class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center"  class="font2">Batuk dan Pilek</p>
                    </div>
                </div>
                <div class="col-lg-4 mx-auto">
                    <p align="center"><img src="{% static 'farah/img/tenggorokan.png' %}" width ="290" height = "200"  class="img3 rounded-circle"> </p>
                    <div align="center">
                        <p align="center"  class="font2">Sakit Tenggorokan</p>
                    </div>
                </div>
            </div>
        </div>
        <br>
            <br>
            <br>
            
            <div>
            <div align="center">
                <h2 align="center" class="border font1">Situs Penting</h2>
            </div> 
            
            <div class="row">
                <div class="col-lg-6 mx-auto">
                    <br>
                    <br>
                    <br>
                    <p align="center"> <img src="{% static 'farah/img/logo menkes.png' %}" width="100%" height="100%" > </p>
                    <div align="center">
                        <br>
                        <p align="center"  class="font2">Website ini tidak hanya berisi 
                            <br>informasi mengenai penyebaran 
                            <br>virus corona di Indonesia dan global, 
                            <br>melainkan juga memuat informasi 
                            <br>penyakit infeksi baru di Indonesia.</p>
                            <a href="https://covid19.kemkes.go.id/category/situasi-infeksi-emerging/info-corona-virus/#.X5RK1IgzZPY"><button align="center" class="button">cek disini</button> </a>
                            <br>
                        </div>
                </div>
                
                <div class="col-lg-6 mx-auto">
                    <br>
                    <br>
                    <br>
                    <p align="center"><img src="{% static 'farah/img/logo satgas.png' %}" width="60%" height="60%" > </p>
                    <div align="center">
                        <p align="center"  class="font2">Website ini berisi tentang virus 
                            <br>corona yang dapat diakses oleh 
                            <br>masyarakat Indonesia supaya 
                            <br>mengetahui perkembangan virus 
                            <br>corona di tanah air.</p>
                            <a href="https://covid19.go.id/"><button align = "center" class="button">cek disini</button> </a>
                            <br>
                        </div>
                </div>
            </div>
        </div>
        <br>
        <br>
        <br>
        <br>
        <div>
        <p align = "center" class = "font3">Menurut kalian, apa saja sih kegiatan yang
        <br>dapat dilakukan selama pandemi berlangsung?</p>
            <div align="center" class="container pt-3" margin="20px">
        <form action='' method="POST" margin="20px">
            {% csrf_token %}
            {{ Form }}
            <div align="center" >
                <input type="submit" class="button" value="Submit">
            </div>
        </form>

        <br>
        <br>
        <br>

        <a href="{% url 'farah:listkegiatan' %}"><button align="center" class="button">Cek Kegiatan</button> </a>
            </div>
       
    {% endblock content %}

farah/templates/farah/listkegiatan.html
{% extends 'global/base.html' %}
{% load static %}

{% block meta %}
<title>List Kegiatan</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>
<style>
      body{
        background-color: #A8D0E6 ;
    }
    .button {
        background-color: #374785;
        border-radius: 15px;
        padding: 10px 24px;
        text-align: center;
        color: white;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        font-family: "Poppins";
        font-weight: bold;
    }

    .button:hover {
        background-color: white;
        color: #374785;
    }

    .border {
        border: solid;
        width: 450px;
        height: 45px;
        background: #374785;
        border-radius: 50px;
    }

    .font1 {
        font-family: Georgia, 'Times New Roman', Times, serif;
        font-size: 30px;
        font-weight: bold;
        color: white;
    }

    .font2 {
        font-family: 'Poppins';
        font-size: 22px;
        color: #374785;
        font-weight: 900;
    }

    .font3 {
        font-family: Georgia, 'Times New Roman', Times, serif;
        font-size: 34px;
        font-weight: bold;
        color: #374785;
    }

     .font4 {
        font-family: 'Poppins';
        font-size: 22px;
        color: #F76C6C;
        font-weight: bold;
        font-style: italic;
        font-weight: 900;
    }

    .border1{
	border: solid 3px #374785; 
	border-radius: 50px;
    background: white;
     grid-row-gap: 2px;
    grid-column-gap: 5px;
    }
</style>
{% endblock meta %}

{% block content %}

<br>
<br>
<br>
<br>
<h1 align="center" class="font3">  Kegiatan yang dapat dilakukan
    <br> selama pandemi berlangsung: </h1>
    <br>
    <br>



{% for x in listkegiatan %}
   <p align = "center" class = "border1 font4"> {{x.nama_kegiatan}} </p>
{% endfor %}



<br>
<div align = "center">
<a href="{% url 'farah:edukasi' %}"><button align="center" class="button">Kembali</button> </a>
</div>
{% endblock content %}